version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: stellaranvil-postgres
    environment:
      POSTGRES_DB: stellaranvil
      POSTGRES_USER: stellaranvil
      POSTGRES_PASSWORD: stellaranvil123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - stellaranvil-network

  prometheus:
    image: prom/prometheus:latest
    container_name: stellaranvil-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - stellaranvil-network

  grafana:
    image: grafana/grafana:latest
    container_name: stellaranvil-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - stellaranvil-network

  loki:
    image: grafana/loki:latest
    container_name: stellaranvil-loki
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki:/etc/loki
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - stellaranvil-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: stellaranvil-jaeger
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
    environment:
      COLLECTOR_OTLP_ENABLED: true
    networks:
      - stellaranvil-network

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
  loki_data:

networks:
  stellaranvil-network:
    driver: bridge
